import 'package:flutter/material.dart';


import '../../../services/agora_service.dart';

enum VideoEffectsSection {
  presets,
  beauty,
  makeup,
  filter,
}

class VideoEffectLook {
  const VideoEffectLook({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.colors,
    required this.lightening,
    required this.smoothness,
    required this.redness,
    required this.sharpness,
    required this.colorStrength,
    required this.skinProtect,
    required this.filter,
    this.filterStrength = .58,
    this.lowLight = true,
    this.denoise = true,
  });

  final String id;
  final String title;
  final String subtitle;
  final List<Color> colors;
  final double lightening;
  final double smoothness;
  final double redness;
  final double sharpness;
  final double colorStrength;
  final double skinProtect;
  final AgoraLutFilter filter;
  final double filterStrength;
  final bool lowLight;
  final bool denoise;
}

const VideoEffectLook noEffectLook = VideoEffectLook(
  id: 'none',
  title: 'None',
  subtitle: 'Original',
  colors: <Color>[Color(0xFF4C4D52), Color(0xFF24252A)],
  lightening: 0,
  smoothness: 0,
  redness: 0,
  sharpness: 0,
  colorStrength: 0,
  skinProtect: 0,
  filter: AgoraLutFilter.none,
  filterStrength: 0,
  lowLight: false,
  denoise: false,
);

const List<VideoEffectLook> professionalPresets = <VideoEffectLook>[
  VideoEffectLook(
    id: 'smart_beauty',
    title: 'Smart Beauty',
    subtitle: 'Balanced',
    colors: <Color>[Color(0xFFBFF5E9), Color(0xFF83D4C8)],
    lightening: .48,
    smoothness: .50,
    redness: .18,
    sharpness: .38,
    colorStrength: .24,
    skinProtect: .50,
    filter: AgoraLutFilter.fresh,
    filterStrength: .36,
  ),
  VideoEffectLook(
    id: 'true_skin',
    title: 'True Skin',
    subtitle: 'Natural',
    colors: <Color>[Color(0xFFF4D7C6), Color(0xFFBA8D75)],
    lightening: .40,
    smoothness: .38,
    redness: .14,
    sharpness: .48,
    colorStrength: .16,
    skinProtect: .62,
    filter: AgoraLutFilter.natural,
    filterStrength: .28,
  ),
  VideoEffectLook(
    id: 'oxygen_skin',
    title: 'Oxygen Skin',
    subtitle: 'Fresh',
    colors: <Color>[Color(0xFFD8F7FF), Color(0xFF7BC7D8)],
    lightening: .56,
    smoothness: .45,
    redness: .12,
    sharpness: .48,
    colorStrength: .38,
    skinProtect: .50,
    filter: AgoraLutFilter.fresh,
    filterStrength: .58,
  ),
  VideoEffectLook(
    id: 'sheer_finish',
    title: 'Sheer Finish',
    subtitle: 'Soft',
    colors: <Color>[Color(0xFFFFDCE8), Color(0xFFD59AAF)],
    lightening: .58,
    smoothness: .68,
    redness: .20,
    sharpness: .30,
    colorStrength: .20,
    skinProtect: .62,
    filter: AgoraLutFilter.rosy,
    filterStrength: .38,
  ),
  VideoEffectLook(
    id: 'studio_hd',
    title: 'Studio HD',
    subtitle: 'Clear',
    colors: <Color>[Color(0xFFE9E9F4), Color(0xFF8589A8)],
    lightening: .52,
    smoothness: .42,
    redness: .16,
    sharpness: .72,
    colorStrength: .36,
    skinProtect: .52,
    filter: AgoraLutFilter.studio,
    filterStrength: .56,
  ),
  VideoEffectLook(
    id: 'warm_glow',
    title: 'Warm Glow',
    subtitle: 'Warm',
    colors: <Color>[Color(0xFFFFD29D), Color(0xFFC67A52)],
    lightening: .48,
    smoothness: .45,
    redness: .30,
    sharpness: .42,
    colorStrength: .28,
    skinProtect: .52,
    filter: AgoraLutFilter.warm,
    filterStrength: .64,
  ),
];

const List<VideoEffectLook> makeupLooks = <VideoEffectLook>[
  VideoEffectLook(
    id: 'sakura_glow',
    title: 'Sakura Glow',
    subtitle: 'Pink glow',
    colors: <Color>[Color(0xFFFFD7E5), Color(0xFFB56C91)],
    lightening: .58,
    smoothness: .62,
    redness: .38,
    sharpness: .34,
    colorStrength: .26,
    skinProtect: .55,
    filter: AgoraLutFilter.rosy,
    filterStrength: .58,
  ),
  VideoEffectLook(
    id: 'peach',
    title: 'Peach',
    subtitle: 'Peach tone',
    colors: <Color>[Color(0xFFFFC69E), Color(0xFFD57859)],
    lightening: .54,
    smoothness: .56,
    redness: .32,
    sharpness: .38,
    colorStrength: .30,
    skinProtect: .50,
    filter: AgoraLutFilter.warm,
    filterStrength: .54,
  ),
  VideoEffectLook(
    id: 'golden_muse',
    title: 'Golden Muse',
    subtitle: 'Warm studio',
    colors: <Color>[Color(0xFFFFD28B), Color(0xFF9E6542)],
    lightening: .50,
    smoothness: .48,
    redness: .25,
    sharpness: .50,
    colorStrength: .35,
    skinProtect: .48,
    filter: AgoraLutFilter.warm,
    filterStrength: .72,
  ),
  VideoEffectLook(
    id: 'silver_siren',
    title: 'Silver Siren',
    subtitle: 'Cool clear',
    colors: <Color>[Color(0xFFDDE8FF), Color(0xFF7787AC)],
    lightening: .56,
    smoothness: .54,
    redness: .12,
    sharpness: .55,
    colorStrength: .32,
    skinProtect: .54,
    filter: AgoraLutFilter.cool,
    filterStrength: .62,
  ),
  VideoEffectLook(
    id: 'soft_lip',
    title: 'Soft Rose',
    subtitle: 'Soft finish',
    colors: <Color>[Color(0xFFFFB5CB), Color(0xFF9B5A70)],
    lightening: .52,
    smoothness: .70,
    redness: .42,
    sharpness: .28,
    colorStrength: .20,
    skinProtect: .68,
    filter: AgoraLutFilter.rosy,
    filterStrength: .48,
  ),
  VideoEffectLook(
    id: 'defined',
    title: 'Defined',
    subtitle: 'Sharper detail',
    colors: <Color>[Color(0xFFE1D6CF), Color(0xFF756D68)],
    lightening: .42,
    smoothness: .30,
    redness: .16,
    sharpness: .82,
    colorStrength: .26,
    skinProtect: .46,
    filter: AgoraLutFilter.studio,
    filterStrength: .45,
  ),
];

const List<VideoEffectLook> colorFilterLooks = <VideoEffectLook>[
  VideoEffectLook(
    id: 'filter_warm',
    title: 'Warm',
    subtitle: 'Golden',
    colors: <Color>[Color(0xFFFFC26C), Color(0xFF99572F)],
    lightening: .38,
    smoothness: .28,
    redness: .24,
    sharpness: .40,
    colorStrength: .30,
    skinProtect: .42,
    filter: AgoraLutFilter.warm,
    filterStrength: .72,
  ),
  VideoEffectLook(
    id: 'filter_saturated',
    title: 'Saturated',
    subtitle: 'Vivid',
    colors: <Color>[Color(0xFF7B8CFF), Color(0xFFFF5C8A)],
    lightening: .38,
    smoothness: .24,
    redness: .18,
    sharpness: .46,
    colorStrength: .48,
    skinProtect: .38,
    filter: AgoraLutFilter.saturated,
    filterStrength: .72,
  ),
  VideoEffectLook(
    id: 'filter_fresh',
    title: 'Fresh',
    subtitle: 'Clean',
    colors: <Color>[Color(0xFF91F2E8), Color(0xFF418F9A)],
    lightening: .46,
    smoothness: .30,
    redness: .10,
    sharpness: .48,
    colorStrength: .40,
    skinProtect: .50,
    filter: AgoraLutFilter.fresh,
    filterStrength: .64,
  ),
  VideoEffectLook(
    id: 'filter_cool',
    title: 'Cool',
    subtitle: 'Blue tone',
    colors: <Color>[Color(0xFFC8DEFF), Color(0xFF5E6EA8)],
    lightening: .40,
    smoothness: .26,
    redness: .08,
    sharpness: .50,
    colorStrength: .30,
    skinProtect: .48,
    filter: AgoraLutFilter.cool,
    filterStrength: .70,
  ),
  VideoEffectLook(
    id: 'filter_rosy',
    title: 'Rosy',
    subtitle: 'Pink tone',
    colors: <Color>[Color(0xFFFFB9D0), Color(0xFF9A5D79)],
    lightening: .42,
    smoothness: .34,
    redness: .34,
    sharpness: .40,
    colorStrength: .28,
    skinProtect: .54,
    filter: AgoraLutFilter.rosy,
    filterStrength: .66,
  ),
  VideoEffectLook(
    id: 'filter_studio',
    title: 'Studio',
    subtitle: 'Contrast',
    colors: <Color>[Color(0xFFF2F2F4), Color(0xFF575965)],
    lightening: .42,
    smoothness: .24,
    redness: .14,
    sharpness: .66,
    colorStrength: .36,
    skinProtect: .46,
    filter: AgoraLutFilter.studio,
    filterStrength: .64,
  ),
  VideoEffectLook(
    id: 'filter_cinema',
    title: 'Cinema',
    subtitle: 'Movie look',
    colors: <Color>[Color(0xFF78B8B3), Color(0xFFC17748)],
    lightening: .34,
    smoothness: .20,
    redness: .16,
    sharpness: .62,
    colorStrength: .42,
    skinProtect: .40,
    filter: AgoraLutFilter.cinematic,
    filterStrength: .76,
  ),
];
